---
# Setup LAMP Stack
-  hosts: "{{ variable_host | default('all') }}"
   become: true
   pre_tasks:
    - pause: seconds=30
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
      ignore_errors: yes
   tasks:

      - name: Install tools for adding PPA repositories
        apt:
          name: software-properties-common
          state: latest

      -  name: Add ppa repository
         apt_repository: repo=ppa:ondrej/php
